name: Download Bing Wallpaper

on:
  schedule:
    - cron: "0 17 * * *" # 北京时间凌晨1点触发（UTC+8）
  workflow_dispatch: # 手动触发

jobs:
  update-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm install

      - name: Run Bing Wallpaper Script (ts-node)
        run: |
          echo "Running Bing Wallpaper script with ts-node..."
          npx ts-node src/index.ts

      - name: Format public folder with Prettier
        run: |
          echo "Formatting public folder with Prettier..."
          npx prettier --write "public/**/*.md" "public/**/*.json"

      - name: Commit and push Markdown/JSON file
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Committing and pushing Markdown/JSON file..."
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git add public/wallpapers/.
          # 设置时区为北京时间（UTC+8）
          export TZ=Asia/Shanghai
          git commit -m "Update Bing wallpaper Markdown for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
