name: Download Bing Wallpaper

on:
  schedule:
    - cron: "0 1 * * *" # 每日凌晨1点触发
  workflow_dispatch: # 手动触发

jobs:
  download-wallpaper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pnpm install

      - name: Compile TypeScript
        run: |
          echo "Compiling TypeScript..."
          npx tsc

      - name: Download Bing Wallpaper
        run: |
          echo "Downloading Bing Wallpaper..."
          if ! node dist/index.js; then
            echo "Failed to download Bing wallpaper"
            exit 1
          fi

      - name: Commit and push wallpaper
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Committing and pushing wallpaper..."
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git config --local user.name $GIT_USER_NAME
          git config --local user.email $GIT_USER_EMAIL
          git add public/wallpapers/
          git commit -m "Add Bing wallpaper for $(date +'%Y-%m-%d')"
          git push
